disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - empty_string

excluded:
  - Carthage
  - Pods
  - fastlane
  - .build
  - .github

line_length:
  warning: 120
  error: 200

type_body_length:
  - 300 # warning
  - 400 # error

file_length:
  warning: 500
  error: 1200
